### ISSUE TITLE
eslint-config-airbnb dependency

### ISSUE THREAD

**Issue by TrySound** [tinchoz49/eslint-config-tinchoz49#1]
eslint-config-tinchoz49 depends on eslint-config-airbnb. Why you didn't add it in dependencies?

**Comment by TrySound** [comment]
The same with eslint-plugin-react. Peer dependencies is deprecated and useless feature.

**Comment by TrySound** [comment]
Hm.. don't you think stop depends on `eslint-config-airbnb`? Seems like it's not good example of config. eslint can process a lot of stuff without babel-eslint, plugin-react and more.

**Comment by tinchoz49** [comment]
yes, this is something I want to change some time ago. Replace eslint-config-airbnb by eslint-config-postcss.
